sudo: required
dist: trusty

language: python

matrix:
  allow_failures:
    - os: linux
      python: "3.5"
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.6"
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.7"
      dist: xenial
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.8"
      dist: xenial
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.7"
      dist: xenial
      sudo: required
      env: CONDA=Y CONDAPY=3.7
    - os: linux
      python: "3.8"
      dist: xenial
      sudo: required
      env: CONDA=Y CONDAPY=3.8

    - os: osx
      language: generic
      env: OSXENV=2.7 CONDA=Y CONDAPY=2.7
    - os: osx
      language: generic
      env: OSXENV=3.6 CONDA=Y CONDAPY=3.6
    - os: osx
      language: generic
      env: OSXENV=3.7 CONDA=Y CONDAPY=3.7
    - os: osx
      language: generic
      env: OSXENV=3.8 CONDA=Y CONDAPY=3.8

  include:
    - os: linux
      python: "2.7_with_system_site_packages"
      sudo: required
      env: CONDA=N

    - os: linux
      python: "3.5"
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.6"
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.7"
      dist: xenial
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.8"
      dist: xenial
      sudo: required
      env: CONDA=N

    - os: linux
      python: "2.7"
      sudo: required
      env: CONDA=Y CONDAPY=2.7
    - os: linux
      python: "3.5"
      sudo: required
      env: CONDA=Y CONDAPY=3.5
    - os: linux
      python: "3.6"
      sudo: required
      env: CONDA=Y CONDAPY=3.6
    - os: linux
      python: "3.7"
      dist: xenial
      sudo: required
      env: CONDA=Y CONDAPY=3.7
    - os: linux
      python: "3.8"
      dist: xenial
      sudo: required
      env: CONDA=Y CONDAPY=3.8

    - os: osx
      language: generic
      env: OSXENV=2.7 CONDA=Y CONDAPY=2.7
    - os: osx
      language: generic
      env: OSXENV=3.6 CONDA=Y CONDAPY=3.6
    - os: osx
      language: generic
      env: OSXENV=3.7 CONDA=Y CONDAPY=3.7
    - os: osx
      language: generic
      env: OSXENV=3.8 CONDA=Y CONDAPY=3.8


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash resources/install_osx_virtualenv.sh; fi
  - if [[ "$CONDA" == "N" ]]; then bash resources/install_dependencies.sh; fi
  - if [[ "$CONDA" == "Y" ]]; then bash resources/install_conda.sh; fi

install:
  - if [[ "$CONDA" == "Y" ]]; then
      export PATH="$HOME/miniconda/bin:$PATH";
      source activate condaenv;
    fi
  - which python
  - python setup.py install

script:
  - which python
  # Make sure dependency tests run before the test bulk.
  - python -m unittest test.test_dependencies.TestDependencies
  - python setup.py test
