sudo: required
dist: trusty 

language: python

env:
    global:
        - DISTUTILS_DEBUG=True

matrix:
    include:
        - python: "3.4"

install:
  - sudo bash install_dependencies.sh 
  - python setup.py install

script:
  - python test/check_resources.py
