sudo: required
dist: trusty

language: python

matrix:
  allow_failures:
    - os: linux
      python: "3.5"
      sudo: required
      env: CONDA=N

    - os: osx
      language: generic
      env:
        - OSXENV=2.7
        - CONDA=N

    - os: osx
      language: generic
      env:
        - OSXENV=3.5
        - CONDA=N

  include:
    - os: linux
      python: "2.7_with_system_site_packages"
      sudo: required
      env: CONDA=N

    - os: linux
      python: "2.7"
      sudo: required
      env:
        - CONDA=Y
        - CONDAPY=2.7

    - os: linux
      python: "3.5"
      sudo: required
      env:
        - CONDA=Y
        - CONDAPY=3.5

    - os: osx
      language: generic
      env:
        - OSXENV=2.7
        - CONDA=Y
        - CONDAPY=2.7

    - os: osx
      language: generic
      env:
        - OSXENV=3.5
        - CONDA=Y
        - CONDAPY=3.5

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash resources/install_osx_virtualenv.sh; fi
  - if [[ "$CONDA" == "N" ]]; then bash resources/install_dependencies.sh; fi
  - if [[ "$CONDA" == "Y" ]]; then bash resources/install_conda.sh; fi

install:
  - if [[ "$CONDA" == "Y" ]]; then
      export PATH="$HOME/miniconda/bin:$PATH";
      source activate condaenv;
    fi
  - which python
  - python setup.py install

script:
  - which python
  - python setup.py test
