sudo: required
dist: trusty

language: python

env:
    global:
        - DISTUTILS_DEBUG=True

matrix:
    include:
        - os: linux
          python: "3.4"
        - os: linux
          python: "2.7"
        # - os: osx
        #  env: TOXENV=py34
        # - os: osx
        #  env: TOXENV=py27

install:
  - sudo bash install_dependencies.sh 
  - python setup.py install

script:
  - python test/check_resources.py
