sudo: required
dist: trusty

language: python

matrix:

  include:
    - os: linux
      python: "3.8"
      dist: xenial
      sudo: required
      env: CONDA=Y CONDAPY=3.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash resources/install_osx_virtualenv.sh; fi
  - if [[ "$CONDA" == "N" ]]; then bash resources/install_dependencies.sh; fi
  - if [[ "$CONDA" == "Y" ]]; then bash resources/install_conda.sh; fi

install:
  - if [[ "$CONDA" == "Y" ]]; then
    export PATH="$HOME/miniconda/bin:$PATH";
    source activate condaenv;
    fi
  - which python
  - python setup.py install

script:
  - which python
  # Make sure dependency tests run before the test bulk.
  - python -m unittest test.test_dependencies.TestDependencies
  - python setup.py test
